# Generated by Django 4.2.7 on 2025-05-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["year", "make", "model", "generation", "trim"]},
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="generation",
            field=models.CharField(
                blank=True,
                help_text="Model generation (e.g., 'Gen 3', '2nd Gen', 'Mk IV') - use when generation affects parts compatibility",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("year", "make", "model", "generation", "trim", "engine")},
        ),
    ]
