# Generated by Django for Part Groups implementation

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('voltage', models.DecimalField(blank=True, decimal_places=1, help_text='Voltage (e.g., 12.0)', max_digits=5, null=True)),
                ('amperage', models.DecimalField(blank=True, decimal_places=1, help_text='Amperage/Current rating', max_digits=6, null=True)),
                ('wattage', models.DecimalField(blank=True, decimal_places=1, help_text='Power rating in watts', max_digits=8, null=True)),
                ('mounting_pattern', models.CharField(blank=True, help_text='Bolt pattern, mounting configuration', max_length=100)),
                ('connector_type', models.CharField(blank=True, help_text='Electrical connector type', max_length=100)),
                ('thread_size', models.CharField(blank=True, help_text='Thread size for bolts/fittings', max_length=50)),
                ('max_length', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum length in inches', max_digits=6, null=True)),
                ('max_width', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum width in inches', max_digits=6, null=True)),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum height in inches', max_digits=6, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Additional technical specifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_groups', to='parts.partcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_level', models.CharField(choices=[('IDENTICAL', 'Identical - Direct replacement'), ('COMPATIBLE', 'Compatible - Same function, minor differences'), ('CONDITIONAL', 'Conditional - Requires modification/adaptation')], default='COMPATIBLE', max_length=20)),
                ('part_voltage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('part_amperage', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('part_wattage', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('installation_notes', models.TextField(blank=True, help_text='Specific installation requirements or compatibility notes')),
                ('year_restriction', models.CharField(blank=True, help_text="Year range restriction (e.g., '2005-2010')", max_length=20)),
                ('application_restriction', models.CharField(blank=True, help_text='Specific application restrictions', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Has this compatibility been verified?')),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_group_memberships', to='parts.part')),
                ('part_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='parts.partgroup')),
            ],
            options={
                'ordering': ['compatibility_level', 'part__part_number'],
                'unique_together': {('part', 'part_group')},
            },
        ),
    ]
