# Generated by Django for eBay Marketplace Account Deletion compliance

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(help_text='32-80 character verification token for eBay notifications', max_length=80)),
                ('endpoint_url', models.URLField(help_text='The notification endpoint URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_notification_config',
            },
        ),
        migrations.CreateModel(
            name='EbayAccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('eias_token', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_attempt_count', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_data_summary', models.TextField(blank=True, help_text='Summary of what data was deleted for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_account_deletion_log',
                'ordering': ['-received_date'],
            },
        ),
        migrations.AddIndex(
            model_name='ebayaccountdeletionlog',
            index=models.Index(fields=['username'], name='ebay_accoun_usernam_b6c6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayaccountdeletionlog',
            index=models.Index(fields=['user_id'], name='ebay_accoun_user_id_ae31d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayaccountdeletionlog',
            index=models.Index(fields=['notification_id'], name='ebay_accoun_notific_3b4e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayaccountdeletionlog',
            index=models.Index(fields=['processed'], name='ebay_accoun_process_c44d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayaccountdeletionlog',
            index=models.Index(fields=['received_date'], name='ebay_accoun_receive_0b9af4_idx'),
        ),
    ]
