# Generated by Django 4.2.7 on 2025-06-15 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebay_notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ebayaccountdeletionlog",
            new_name="ebay_accoun_usernam_ae8f13_idx",
            old_name="ebay_accoun_usernam_b6c6e4_idx",
        ),
        migrations.RenameIndex(
            model_name="ebayaccountdeletionlog",
            new_name="ebay_accoun_user_id_213267_idx",
            old_name="ebay_accoun_user_id_ae31d4_idx",
        ),
        migrations.RenameIndex(
            model_name="ebayaccountdeletionlog",
            new_name="ebay_accoun_notific_80c6a4_idx",
            old_name="ebay_accoun_notific_3b4e0e_idx",
        ),
        migrations.RenameIndex(
            model_name="ebayaccountdeletionlog",
            new_name="ebay_accoun_process_29cde0_idx",
            old_name="ebay_accoun_process_c44d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="ebayaccountdeletionlog",
            new_name="ebay_accoun_receive_be74e4_idx",
            old_name="ebay_accoun_receive_0b9af4_idx",
        ),
    ]
